#!/bin/sh
# Profile file. Runs on login.

export EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="urxvt"


# Start X graphical server
if [[ ! $DISPLAY && $(tty) == /dev/tty1 ]]; then
    exec startx &> ~/.Xlog
fi
