#!/bin/sh
# Xorg configuration file.

# Set keyboard
setxkbmap \
    -model 'pc105' \
    -layout 'us(dvp),us' \
    -option 'grp:win_space_toggle' \
    -option 'caps:escape'

# Merge Xresources
[ -f "$HOME/.Xresources" ] && xrdb -merge ~/.Xresources

# Appearance
xbacklight -set 30  # Set backlight
xset b off          # Turn bell off

# Execute i3wm
exec i3
