# Zsh environment file. Alway runs.

# Exports
export EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="urxvt"

# Default path
PATH="/bin:/usr/bin:/usr/local/bin:$HOME/.local/bin"

# Custom Paths
if [[ -d "$HOME/.cargo/bin" ]]; then
    PATH="$PATH:$HOME/.cargo/bin"
fi

