#--------------#
# Key Bindings #
#--------------#
#xmodmap ~/.Xmodmap

if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    exec startx &> ~/.Xlog
fi

export CHROMIUM_FLAGS='--enable-remote-extensions'
